version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "In install phase..."
      - echo "Installing frontend dependencies..."
      - cd frontend && npm install && cd ..
      - echo "Installing backend dependencies..."
      - cd backend && npm install && cd ..
  build:
    commands:
      - echo "In build phase..."
  post_build:
    commands:
      - echo "In post_build phase..."
